#this code is generated by Google Gemini
# this code will contain a path to a .npy file(Lidar Scan) which will not be uploaded to github since it is confidential data of valeo.

import open3d as o3d

# 1. Load the NPI lidar scan
scan = o3d.io.read_point_cloud("./")

# 2. Access the first frame
first_frame = scan.frames[0]

# 3. Visualize using Open3D
o3d.visualization.draw_geometries([first_frame])